### ISSUE TITLE
Possible install script issue

### ISSUE THREAD

**Issue by bigusbeckus** [Joakker/lua-json5#2]
Hey @Joakker, thank you for this package! I'm trying to setup nvim-dap to use configs from `.vscode/launch.json` and this makes it so I don't have to worry about comments or trailing commas!

I ran into a `module 'json5' not found` error after installing through packer and adding `./lua/?.so` to `package.cpath` and managed to track it down to the install script.

The `OSTYPE` environment variable isn't recognized on some distros (like Ubuntu) when using `#!/bin/sh`. In this case, it meant the `json5.so` file wasn't actually being copied to the lua folder like it should be. Changing that to `#!/bin/bash` fixes the issue and should be fine on distros that ship with bash (which is most of them) and MacOS (as far as I can tell from searching, I don't have a Mac to test on). Didn't make a PR in case you wanna handle it differently.

**Comment by Joakker** [comment]
Sorry for the long wait, I'll do it right away

**Comment by Joakker** [comment]
Please update it and try it now

**Comment by bigusbeckus** [comment]
Works great now, thanks! :smile:

**Comment by Freed-Wu** [comment]
Compared to install scripts, why not let user `luarocks install lua-json5` to install it?
- mlua has support  for luarocks https://github.com/mlua-rs/luarocks-build-rust-mlua
- many neovim plugins exist in luarocks https://luarocks.org/labels/neovim
- there exists neovim plugin managers to use luarocks to install vim plugins [rocks.nvim](https://github.com/lumen-oss/rocks.nvim), [lazy.nvim](https://lazy.folke.io/packages#rockspec)

**Comment by Joakker** [comment]
Huh, interesting, I'll look into it

**Comment by Freed-Wu** [comment]
Here is an [example](https://github.com/pxwg/math-conceal.nvim) to use luarocks-build-rust-mlua to build vim plugin and install it by lazy.nvim/rocks.nvim.
