### ISSUE TITLE
`module 'json5' not found` on MacOS

### ISSUE THREAD

**Issue by instantepiphany** [Joakker/lua-json5#4]
Following on from the request in #1 https://github.com/Joakker/lua-json5/issues/1#issuecomment-1378908180

Is providing a `.so` instead of a `.dylib` on MacOS feasible? 

Right now the install instructions don't work on mac, the module isn't found, unless a specific workaround is added, renaming the `json5.dylib` to `json5.so` or adding the hardcoded path to the dylib, or adding a lua function that finds and replaces the existing `.so` entries with equivalent `.dylib` ones.
https://github.com/neovim/neovim/issues/21749#issuecomment-1418427487

From that issue, it seems neovim (really, luajit) will not support loading `dylib`, and expect packages to always provide `.so` on linux/unix.

**Comment by Joakker** [comment]
Yeah, the reason why I provide a `.dylib` module is because at the time luajit complained precisely that it needed a library with that extension. I'll fix it right now

**Comment by instantepiphany** [comment]
Thanks very much!
